# Generated by Django 3.0.5 on 2020-07-08 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_auto_20200708_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, upload_to='images/profile/'),
        ),
    ]
