# Generated by Django 3.0.5 on 2020-07-17 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0004_auto_20200717_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
    ]
