# Generated by Django 3.0.5 on 2020-07-21 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0005_remove_user_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo',
        ),
    ]
