# Generated by Django 3.0.5 on 2020-04-27 23:57

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('home', '0004_tutordetailpage_tutorspage'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetailpage',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursedetailpage',
            name='course_url',
            field=models.CharField(blank=True, max_length=2048, null=True),
        ),
        migrations.AddField(
            model_name='coursedetailpage',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Beginner'), (1, 'Easy'), (2, 'Medium'), (3, 'Hard'), (4, 'Advanced')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursedetailpage',
            name='duration_hours',
            field=models.PositiveSmallIntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursedetailpage',
            name='images',
            field=wagtail.core.fields.StreamField([('image', wagtail.images.blocks.ImageChooserBlock(required=False))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursedetailpage',
            name='overview',
            field=wagtail.core.fields.RichTextField(default='default overview'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursedetailpage',
            name='provider',
            field=models.CharField(default='default provider', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursedetailpage',
            name='summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CourseTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_object', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagged_items', to='home.CourseDetailPage')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_coursetag_items', to='taggit.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='coursedetailpage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='home.CourseTag', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
