# Generated by Django 3.0.5 on 2020-04-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20200430_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetailpage',
            name='cost',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='coursedetailpage',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Beginner'), (1, 'Easy'), (2, 'Medium'), (3, 'Hard'), (4, 'Advanced')], db_index=True),
        ),
        migrations.AlterField(
            model_name='coursedetailpage',
            name='duration_hours',
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='coursedetailpage',
            name='provider',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
