# Generated by Django 3.0.5 on 2020-05-01 15:47

from django.db import migrations, models

from home.submodels.course_detail_page import CourseDetailPage

sql = (
    'UPDATE home_coursedetailpage SET avg_score = '
    '(SELECT AVG(score) FROM home_coursereview WHERE course_detail_page_id = page_ptr_id)'
)
reverse_sql = 'UPDATE home_coursedetailpage SET avg_score = null'


class Migration(migrations.Migration):
    dependencies = [
        ('home', '0008_coursereview'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetailpage',
            name='avg_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.RunSQL(sql=sql, reverse_sql=reverse_sql)
    ]
