# Generated by Django 3.0.5 on 2020-05-01 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_coursedetailpage_avg_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereview',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
