# Generated by Django 3.0.5 on 2020-05-01 19:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_coursereview_date_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetailpage',
            name='avg_score',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='description',
            field=models.TextField(db_index=True),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='publish_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='score',
            field=models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='subject',
            field=models.TextField(db_index=True),
        ),
    ]
