# Generated by Django 3.0.5 on 2020-05-02 18:38

from django.db import migrations, models

sql = (
    'UPDATE home_coursedetailpage SET review_count = '
    '(SELECT COUNT(*) FROM home_coursereview WHERE course_detail_page_id = page_ptr_id)'
)
reverse_sql = 'UPDATE home_coursedetailpage SET review_count = null'


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20200501_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetailpage',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
        migrations.RunSQL(sql=sql, reverse_sql=reverse_sql)
    ]
