# Generated by Django 3.0.5 on 2020-05-03 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_coursedetailpage_review_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereview',
            name='publish_date',
            field=models.DateField(auto_now_add=True, db_index=True),
        ),
    ]
