# Generated by Django 3.0.5 on 2020-05-10 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_auto_20200505_0218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereview',
            name='reviewer_type',
            field=models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('teacher', 'Teacher')], max_length=24),
        ),
    ]
