# Generated by Django 3.0.5 on 2020-05-10 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20200510_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursereview',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
    ]
