# Generated by Django 3.0.5 on 2020-05-17 16:29

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_infopage'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursespage',
            name='heading',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
