# Generated by Django 3.0.5 on 2020-05-22 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_coursespage_heading'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursedetailpage',
            old_name='overview',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='coursedetailpage',
            old_name='summary',
            new_name='takeaway',
        ),
        migrations.AlterField(
            model_name='coursedetailpage',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Beginner'), (1, 'Intermediate'), (2, 'Advanced')], db_index=True),
        ),
    ]
