# Generated by Django 3.0.5 on 2020-06-01 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20200526_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedetailpage',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(0, '5-7'), (1, '8-10'), (2, '11-13'), (3, '14-16'), (4, '17+')], db_index=True),
        ),
    ]
