# Generated by Django 3.0.5 on 2020-06-01 00:56

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_auto_20200601_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='course_rank_tables',
            field=wagtail.core.fields.StreamField([('course_rank_table', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(required=False)), ('link', wagtail.core.blocks.PageChooserBlock(required=False)), ('caption', wagtail.core.blocks.CharBlock(required=False)), ('filters', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('column', wagtail.core.blocks.CharBlock()), ('value', wagtail.core.blocks.CharBlock())]))), ('excludes', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('column', wagtail.core.blocks.CharBlock()), ('value', wagtail.core.blocks.CharBlock())]))), ('sorts', wagtail.core.blocks.ListBlock(wagtail.core.blocks.CharBlock())), ('result_count', wagtail.core.blocks.IntegerBlock())]))], blank=True, null=True),
        ),
    ]
