# Generated by Django 3.0.5 on 2020-06-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20200606_1938'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursedetailpage',
            name='subject',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Math', 'Math')], db_index=True, default='Computer Science', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursespage',
            name='subject',
            field=models.CharField(choices=[('Computer Science', 'Computer Science'), ('Math', 'Math')], db_index=True, default='Computer Science', max_length=255),
            preserve_default=False,
        ),
    ]
