# Generated by Django 3.0.5 on 2020-06-11 02:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0027_auto_20200611_0129'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoursesPage',
            new_name='CourseSubjectPage',
        ),
    ]
