# Generated by Django 3.0.5 on 2020-06-11 02:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('taggit', '0003_taggeditem_add_unique_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('home', '0028_auto_20200611_0215'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CourseDetailPage',
            new_name='CoursePage',
        ),
        migrations.RenameField(
            model_name='coursereview',
            old_name='course_detail_page',
            new_name='course_page',
        ),
    ]
