# Generated by Django 3.0.5 on 2020-06-11 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_auto_20200611_0224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepage',
            name='subject',
        ),
    ]
