# Generated by Django 3.0.5 on 2020-06-14 04:58

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_remove_coursepage_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infopage',
            name='info',
        ),
        migrations.AddField(
            model_name='infopage',
            name='body',
            field=wagtail.core.fields.StreamField([('paragraph', wagtail.core.blocks.RichTextBlock()), ('image_row', wagtail.core.blocks.ListBlock(wagtail.images.blocks.ImageChooserBlock()))], default={}),
            preserve_default=False,
        ),
    ]
