# Generated by Django 3.0.5 on 2020-06-16 23:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0032_sitefeedback_sitefeedbackpage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitefeedback',
            options={'verbose_name_plural': 'site feedback'},
        ),
        migrations.RenameField(
            model_name='sitefeedback',
            old_name='category',
            new_name='subject',
        ),
    ]
