# Generated by Django 3.0.5 on 2020-06-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20200616_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepage',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Easy'), (1, 'Medium'), (2, 'Hard')], db_index=True),
        ),
    ]
