# Generated by Django 3.0.5 on 2020-06-20 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_providerpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepage',
            name='provider',
        ),
        migrations.AddField(
            model_name='coursepage',
            name='provider_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.ProviderPage'),
        ),
    ]
