# Generated by Django 3.0.5 on 2020-06-20 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_auto_20200620_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursepage',
            old_name='provider_page',
            new_name='provider',
        ),
    ]
