# Generated by Django 3.0.5 on 2020-06-20 19:07

from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_allproviderspage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursepage',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='coursepage',
            name='duration_hours',
        ),
        migrations.RemoveField(
            model_name='coursepage',
            name='minimum_age',
        ),
        migrations.RemoveField(
            model_name='coursepage',
            name='takeaway',
        ),
        migrations.AddField(
            model_name='coursepage',
            name='age_high',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='coursepage',
            name='age_low',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='coursepage',
            name='cost_amount',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='coursepage',
            name='cost_interval',
            field=models.CharField(blank=True, choices=[('lifetime', 'Lifetime'), ('week', 'Week'), ('month', 'Month'), ('quarter', 'Quarter'), ('year', 'Year')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coursepage',
            name='scheduled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursepage',
            name='total_hours',
            field=models.PositiveSmallIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='coursepage',
            name='unit_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='coursepage',
            name='unit_length_minutes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coursepage',
            name='difficulty',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Easy'), (1, 'Medium'), (2, 'Hard')], db_index=True, null=True),
        ),
    ]
