# Generated by Django 3.0.5 on 2020-06-20 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_auto_20200620_1907'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursepage',
            old_name='total_hours',
            new_name='course_length_hours',
        ),
        migrations.RenameField(
            model_name='coursepage',
            old_name='unit_count',
            new_name='lesson_count',
        ),
        migrations.RenameField(
            model_name='coursepage',
            old_name='unit_length_minutes',
            new_name='lesson_length_minutes',
        ),
    ]
