# Generated by Django 3.0.5 on 2020-06-20 19:41

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.contrib.taggit
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('home', '0043_auto_20200620_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgrammingLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='coursepage',
            name='tags',
        ),
        migrations.DeleteModel(
            name='CourseTag',
        ),
        migrations.AddField(
            model_name='programminglanguage',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.PROTECT, to='home.CoursePage'),
        ),
        migrations.AddField(
            model_name='programminglanguage',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_programminglanguage_items', to='taggit.Tag'),
        ),
        migrations.AddField(
            model_name='platform',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.PROTECT, to='home.CoursePage'),
        ),
        migrations.AddField(
            model_name='platform',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_platform_items', to='taggit.Tag'),
        ),
        migrations.AddField(
            model_name='lessontype',
            name='content_object',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.PROTECT, to='home.CoursePage'),
        ),
        migrations.AddField(
            model_name='lessontype',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_lessontype_items', to='taggit.Tag'),
        ),
        migrations.AddField(
            model_name='coursepage',
            name='lesson_type_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='lesson_types', through='home.LessonType', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='coursepage',
            name='platform_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='platforms', through='home.Platform', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AddField(
            model_name='coursepage',
            name='programming_language_tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', related_name='programming_languages', through='home.ProgrammingLanguage', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
