# Generated by Django 3.0.5 on 2020-06-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_auto_20200628_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseimage',
            name='caption',
            field=models.CharField(default='default', max_length=255),
            preserve_default=False,
        ),
    ]
