# Generated by Django 3.0.5 on 2020-06-29 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_courseimage_caption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursepage',
            name='cost_interval',
            field=models.CharField(blank=True, choices=[('once', 'Lifetime'), ('wk', 'Week'), ('mo', 'Month'), ('qtr', 'Quarter'), ('yr', 'Year')], max_length=255, null=True),
        ),
    ]
