# Generated by Django 3.0.5 on 2020-06-29 02:29

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0047_auto_20200629_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='course_rank_tables',
            field=wagtail.core.fields.StreamField([('course_rank_table', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(required=False)), ('link', wagtail.core.blocks.PageChooserBlock(required=False)), ('caption', wagtail.core.blocks.CharBlock(required=False)), ('courses', wagtail.core.blocks.ListBlock(wagtail.core.blocks.PageChooserBlock(page_type=['home.CoursePage'])))]))], blank=True, null=True),
        ),
    ]
