# Generated by Django 3.0.5 on 2020-07-06 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('home', '0050_allblogspage_blogauthor_blogpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='main_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
