# Generated by Django 3.0.5 on 2020-07-09 10:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0051_auto_20200705_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereview',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='coursereview',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
