# Generated by Django 3.0.5 on 2020-07-06 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_auto_20200706_1059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpage',
            old_name='description',
            new_name='short_description',
        ),
    ]
