# Generated by Django 3.0.5 on 2020-07-06 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0052_auto_20200706_1101'),
    ]

    operations = [
        migrations.AddField(
            model_name='allblogspage',
            name='sub_heading',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
