# Generated by Django 3.0.5 on 2020-07-07 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_allblogspage_sub_heading'),
        ('home', '0051_auto_20200705_1634'),
    ]

    operations = [
    ]
