# Generated by Django 3.0.5 on 2020-07-08 00:34

from django.db import migrations
import home.models.blocks
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0054_merge_20200707_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpage',
            name='body',
            field=wagtail.core.fields.StreamField([('image', home.models.blocks.ImageBlock()), ('text', home.models.blocks.RichTextBlock()), ('course_rank_table', wagtail.core.blocks.StructBlock([('heading', wagtail.core.blocks.CharBlock(required=False)), ('link', wagtail.core.blocks.PageChooserBlock(required=False)), ('caption', wagtail.core.blocks.CharBlock(required=False)), ('courses', wagtail.core.blocks.ListBlock(wagtail.core.blocks.PageChooserBlock(page_type=['home.CoursePage'], required=True)))]))]),
        ),
    ]
