# Generated by Django 3.0.5 on 2020-07-08 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0055_auto_20200708_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursereview',
            name='is_anonymous',
        ),
    ]
