# Generated by Django 3.0.5 on 2020-07-27 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0053_sitefeedback_user'),
        ('home', '0056_remove_coursereview_is_anonymous'),
    ]

    operations = [
    ]
