# Generated by Django 3.0.5 on 2020-08-09 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0056_remove_coursereview_is_anonymous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpage',
            name='short_description',
        ),
    ]
