# Generated by Django 3.0.5 on 2020-07-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_merge_20200713_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereview',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
