# Generated by Django 3.0.5 on 2020-09-07 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0057_remove_blogpage_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='providerpage',
            name='avg_score',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='providerpage',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]
