# Generated by Django 3.0.5 on 2020-07-20 11:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0058_coursereview_is_anonymous'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('course_subjects', models.CharField(choices=[('Computer Science', 'Computer Science'), ('Math', 'Math')], max_length=255, null=True)),
                ('is_accepting_students', models.BooleanField(null=True)),
                ('hourly_rate', models.PositiveIntegerField(null=True)),
                ('timezone', models.CharField(choices=[('UTC−12:00', 'UTC−12:00'), ('UTC−11:00', 'UTC−11:00'), ('UTC−10:00', 'UTC−10:00'), ('UTC−9:30', 'UTC−9:30'), ('UTC−9:00', 'UTC−9:00'), ('UTC−8:00', 'UTC−8:00'), ('UTC−7:00', 'UTC−7:00'), ('UTC−6:00', 'UTC−6:00'), ('UTC−5:00', 'UTC−5:00'), ('UTC−4:00', 'UTC−4:00'), ('UTC−3:30', 'UTC−3:30'), ('UTC−3:00', 'UTC−3:00'), ('UTC−2:00', 'UTC−2:00'), ('UTC−1:00', 'UTC−1:00'), ('UTC−00:00', 'UTC−00:00'), ('UTC+1:00', 'UTC+1:00'), ('UTC+2:00', 'UTC+2:00'), ('UTC+3:00', 'UTC+3:00'), ('UTC+3:30', 'UTC+3:30'), ('UTC+4:00', 'UTC+4:00'), ('UTC+4:30', 'UTC+4:30'), ('UTC+5:00', 'UTC+5:00'), ('UTC+5:30', 'UTC+5:30'), ('UTC+5:45', 'UTC+5:45'), ('UTC+6:00', 'UTC+6:00'), ('UTC+6:30', 'UTC+6:30'), ('UTC+7:00', 'UTC+7:00'), ('UTC+8:00', 'UTC+8:00'), ('UTC+8:45', 'UTC+8:45'), ('UTC+9:00', 'UTC+9:00'), ('UTC+9:30', 'UTC+9:30'), ('UTC+10:00', 'UTC+10:00'), ('UTC+10:30', 'UTC+10:30'), ('UTC+11:00', 'UTC+11:00'), ('UTC+12:00', 'UTC+12:00'), ('UTC+12:45', 'UTC+12:45'), ('UTC+13:00', 'UTC+13:00'), ('UTC+14:00', 'UTC+14:00')], max_length=255, null=True)),
                ('description', models.TextField(null=True)),
                ('avg_score', models.FloatField(blank=True, db_index=True, null=True)),
                ('review_count', models.IntegerField(default=0)),
                ('public', models.BooleanField(default=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TutorReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(db_index=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('publish_date', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('subject', models.TextField(db_index=True)),
                ('description', models.TextField(db_index=True)),
                ('date_modified', models.DateTimeField(auto_now=True, db_index=True)),
                ('reviewer_type', models.CharField(choices=[('student', 'Student'), ('parent', 'Parent'), ('teacher', 'Teacher')], max_length=24)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('is_anonymous', models.BooleanField()),
                ('tutor_page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_reviews', to='home.TutorPage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameModel(
            old_name='TutorsPage',
            new_name='AllTutorsPage',
        ),
        migrations.RemoveField(
            model_name='blogauthor',
            name='image',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='blogpage',
            name='page_ptr',
        ),
        migrations.DeleteModel(
            name='AllBlogsPage',
        ),
        migrations.DeleteModel(
            name='BlogAuthor',
        ),
        migrations.DeleteModel(
            name='BlogPage',
        ),
    ]
