# Generated by Django 3.0.5 on 2020-07-30 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0058_auto_20200729_1007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursereview',
            name='is_anonymous',
        ),
    ]
