# Generated by Django 3.0.5 on 2020-07-22 09:58

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0060_allblogspage_blogauthor_blogpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorpage',
            name='course_subjects',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Computer Science', 'Computer Science'), ('Math', 'Math')], max_length=255, null=True),
        ),
    ]
